QUERIES = [
	"Software Engineer",
	"Data Analyst",
	"Product Manager",
	"UX Designer",
	"QA Engineer",
	"Full Stack Developer",
	"Business Analyst",
	"Project Manager",
	"Graphic Designer",
	"Content Writer",
	"SEO Specialist",
	"Digital Marketer",
	"Civil Engineer",
	"Mechanical Engineer",
	"Electrical Engineer",
	"Accountant",
	"Financial Analyst",
	"HR Executive",
	"Social Media Manager",
	"Customer Support Executive",
	"Technical Support Engineer",
	"Receptionist",
	"Office Assistant",
	"Administrative Officer",
	"Medical Coder",
	"Pharmacist",
	"Nurse",
	"Doctor",
	"Lab Technician",
	"Sales Executive",
	"Marketing Executive",
	"Legal Advisor",
	"Advocate",
	"Compliance Officer",
	"Bank Clerk",
	"SBI PO",
	"Data Scientist",
	"Machine Learning Engineer",
	"AI Researcher",
	"Cloud Engineer",
	"DevOps Engineer",
	"Cybersecurity Analyst",
	"Systems Administrator",
	"Database Administrator",
	"Network Engineer",
	"Video Editor",
	"Animator",
	"Illustrator",
	"Copywriter",
	"Journalist",
	"Teacher",
	"School Principal",
	"Assistant Professor",
	"Lecturer",
	"Research Fellow",
	"Virtual Assistant",
	"Online Tutor",
	"Delivery Executive",
	"Warehouse Manager",
	"Inventory Specialist",
	"Electrician",
	"Plumber",
	"Mechanic",
	"Welder",
	"Machine Operator",
	"Security Guard",
	"Field Sales Officer",
	"Loan Officer",
	"Insurance Advisor",
	"Investment Banker",
	"CA (Chartered Accountant)",
	"Stenographer",
	"Librarian",
	"Data Entry Operator",
	"Telecaller",
	"IT Support Technician",
	"BPO Executive",
	"Voice Process Agent",
	"Back Office Executive",
	"Clerk",
]
