QUERIES = [
    "Account Manager",
    "Accountant",
    "Academic Coordinator",
    "Administrative Officer",
    "AI Researcher",
    "Animator",
    "Area Sales Manager",
    "Assistant Professor",
    "Audit Manager",
    "Back Office Executive",
    "Bank Clerk",
    "BPO Executive",
    "Branch Manager",
    "Brand Manager",
    "Business Analyst",
    "Business Development Manager",
    "CA (Chartered Accountant)",
    "Call Center Supervisor",
    "Campaign Manager",
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "Civil Engineer",
    "Clerk",
    "Cloud Engineer",
    "Cloud Operations Manager",
    "Community Lead",
    "Compliance Officer",
    "Construction Site Coordinator",
    "Content Lead",
    "Content Writer",
    "Copywriter",
    "Crew Leader",
    "Cybersecurity Analyst",
    "Customer Service Team Lead",
    "Customer Support Executive",
    "Customer Success Manager",
    "Data Analyst",
    "Data Entry Operator",
    "Data Scientist",
    "Database Administrator",
    "Delivery Executive",
    "Design Lead",
    "DevOps Engineer",
    "DevOps Lead",
    "Digital Marketing Manager",
    "Digital Marketer",
    "Doctor",
    "Electrical Engineer",
    "Engineering Manager",
    "Executive Director",
    "Field Sales Officer",
    "Field Service Lead",
    "Finance Executive",
    "Finance Manager",
    "Financial Analyst",
    "Fleet Manager",
    "Floor Supervisor",
    "Full Stack Developer",
    "General Manager",
    "Graphic Designer",
    "HOD (Head of Department)",
    "HR Executive",
    "HR Manager",
    "Illustrator",
    "Infrastructure Manager",
    "Insurance Advisor",
    "Inventory Control Manager",
    "Inventory Specialist",
    "Inventory Supervisor",
    "Investment Banker",
    "IT Coordinator",
    "IT Manager",
    "IT Support Technician",
    "Journalist",
    "Junior Project Coordinator",
    "Lab In-Charge",
    "Lab Technician",
    "Lecturer",
    "Legal Advisor",
    "Legal Compliance Officer",
    "Loan Officer",
    "Logistics Executive",
    "Logistics Manager",
    "Machine Learning Engineer",
    "Machine Operator",
    "Maintenance In-Charge",
    "Managing Director",
    "Marketing Executive",
    "Marketing Manager",
    "Mechanical Engineer",
    "Medical Coder",
    "Mechanic",
    "Network Engineer",
    "Nurse",
    "Office Assistant",
    "Office Coordinator",
    "Online Tutor",
    "Operations Executive",
    "Operations Manager",
    "Pharmacist",
    "Plumber",
    "Product Manager",
    "Production Supervisor",
    "Program Manager",
    "Project Manager",
    "Public Relations Manager",
    "QA Engineer",
    "QA Lead",
    "Receptionist",
    "Recruitment Lead",
    "Research Fellow",
    "Risk Manager",
    "Sales Executive",
    "Sales Manager",
    "Sales Supervisor",
    "School Principal",
    "School Vice Principal",
    "Scrum Master",
    "Security Guard",
    "Security Manager",
    "SEO Specialist",
    "Service Delivery Lead",
    "Service Delivery Manager",
    "Shift In-Charge",
    "Shift Supervisor",
    "Site Supervisor",
    "Social Media Manager",
    "Social Media Strategist",
    "Software Engineer",
    "Stenographer",
    "Store Supervisor",
    "Strategy Manager",
    "Support Lead",
    "Support Supervisor",
    "Supply Chain Manager",
    "Systems Administrator",
    "Teacher",
    "Technical Support Engineer",
    "Technical Support Lead",
    "Team Leader",
    "Telecaller",
    "Territory Manager",
    "Training Coordinator",
    "Training Manager",
    "UX Designer",
    "Video Editor",
    "Virtual Assistant",
    "Voice Process Agent",
    "Warehouse Manager",
    "Welder",
    "Zonal Operations Manager",
    "BPO Team Leader",
    "Retail Shift Leader",
    "Field Team Lead",
    "Procurement Executive",
    "Tech Lead",
    "Quality Control Supervisor",
    "Workshop Foreman",
    "Safety Supervisor",
    "Client Relationship Manager",
    "People Operations Manager",
    "Accounting Supervisor",
    "Innovation Manager",
    "Change Management Lead",
    "Transformation Manager",
    "Business Intelligence Manager",
    "Strategy Consultant",
    "Organizational Development Manager",
    "Corporate Affairs Manager",
    "Sustainability Manager",
    "Digital Transformation Lead",
    "Systems Engineering Lead",
    "Robotics Supervisor",
    "Manufacturing Lead",
    "Automation Manager",
    "Tooling Manager",
    "R&D Team Lead",
    "Industrial Engineering Supervisor",
    "Tax Manager",
    "Forensic Audit Specialist",
    "Internal Controls Manager",
    "Credit Control Manager",
    "Cost Accounting Manager",
    "Learning and Development Manager",
    "Employee Relations Specialist",
    "Talent Acquisition Lead",
    "Compensation and Benefits Manager",
    "Market Research Analyst Lead",
    "Corporate Communications Manager",
    "Creative Project Manager",
    "Events Coordinator",
    "Advertising Operations Manager",
    "Government Liaison Officer",
    "Contracts Manager",
    "Ethics and Compliance Officer",
    "Facilities Supervisor",
    "Real Estate Portfolio Manager",
    "Building Maintenance Supervisor",
    "Environmental Health and Safety (EHS) Manager",
    "Health and Safety Officer",
    "Disaster Recovery Coordinator",
    "eLearning Coordinator",
    "Academic Program Manager",
    "Training and Placement Officer",
    "Hotel Operations Manager",
    "Front Office Supervisor",
    "Guest Services Manager",
    "Housekeeping Supervisor",
    "Retail Store Manager",
    "Customer Experience Manager",
    "Cash Office Supervisor",
    "Visual Merchandising Coordinator"
]